//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminkontrol
    {
        public int id { get; set; }
        public Nullable<double> miktar { get; set; }
        public int stok_id { get; set; }
        public Nullable<int> giren { get; set; }
        public Nullable<int> kul_id { get; set; }
        public Nullable<System.DateTime> kayittarih { get; set; }
        public Nullable<int> tur { get; set; }
        public Nullable<int> tedarik { get; set; }
        public Nullable<int> birim { get; set; }
        public Nullable<int> malzeme { get; set; }
        public Nullable<double> harcanan { get; set; }
        public Nullable<double> girilen { get; set; }
    
        public virtual birim birim1 { get; set; }
        public virtual login login { get; set; }
        public virtual malzemelist malzemelist { get; set; }
        public virtual stok stok { get; set; }
        public virtual tedarikci tedarikci { get; set; }
        public virtual tur tur1 { get; set; }
    }
}
