//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gtc_stokEntities2 : DbContext
    {
        public gtc_stokEntities2()
            : base("name=gtc_stokEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminkontrol> adminkontrol { get; set; }
        public virtual DbSet<birim> birim { get; set; }
        public virtual DbSet<cinsiyet> cinsiyet { get; set; }
        public virtual DbSet<giriscikis> giriscikis { get; set; }
        public virtual DbSet<guvenlikkontrol> guvenlikkontrol { get; set; }
        public virtual DbSet<kangrup> kangrup { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<malzemelist> malzemelist { get; set; }
        public virtual DbSet<medenihali> medenihali { get; set; }
        public virtual DbSet<misafir> misafir { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<personelbolum> personelbolum { get; set; }
        public virtual DbSet<personelegitim> personelegitim { get; set; }
        public virtual DbSet<personelgenel> personelgenel { get; set; }
        public virtual DbSet<personelgorev> personelgorev { get; set; }
        public virtual DbSet<personelgrup> personelgrup { get; set; }
        public virtual DbSet<personelsicaklik> personelsicaklik { get; set; }
        public virtual DbSet<stok> stok { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tedarikci> tedarikci { get; set; }
        public virtual DbSet<tur> tur { get; set; }
        public virtual DbSet<yetki> yetki { get; set; }
    
        public virtual ObjectResult<stok_list_Result> stok_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stok_list_Result>("stok_list");
        }
    }
}
