//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guvenlikkontrol
    {
        public int id { get; set; }
        public Nullable<int> kul_id { get; set; }
        public Nullable<System.DateTime> kayittarih { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> misafir_id { get; set; }
        public Nullable<int> durum { get; set; }
    
        public virtual login login { get; set; }
        public virtual misafir misafir { get; set; }
        public virtual personel personel { get; set; }
    }
}
