//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public login()
        {
            this.adminkontrol = new HashSet<adminkontrol>();
            this.stok = new HashSet<stok>();
            this.guvenlikkontrol = new HashSet<guvenlikkontrol>();
        }

        public int id { get; set; }
        public string name { get; set; }
        [DataType(DataType.Password)]
        public string pass { get; set; }
        public Nullable<int> status { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string VCode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adminkontrol> adminkontrol { get; set; }
        public virtual yetki yetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stok> stok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guvenlikkontrol> guvenlikkontrol { get; set; }
        public string lgnerror { get; set; }
    }
}
