//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class personelgenel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personelgenel()
        {
            this.giriscikis = new HashSet<giriscikis>();
            this.personel = new HashSet<personel>();
            this.personelsicaklik = new HashSet<personelsicaklik>();
        }
        [Required(ErrorMessage = "Boþ Býrakmayýn")]
        public int kart_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<int> grup_id { get; set; }
        public Nullable<int> bolum_id { get; set; }
        public Nullable<int> gorev_id { get; set; }
        public Nullable<int> egitim_id { get; set; }
        public string bankahesapno { get; set; }
        public string telefon { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> baslamatarihi { get; set; }
        public string tc { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> resmibaslamatarihi { get; set; }
        public Nullable<int> isdisable { get; set; }
        public string anaadi { get; set; }
        public string babaadi { get; set; }
        public string serino { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> dogumtarih { get; set; }
        public Nullable<short> medenihali_id { get; set; }
        public Nullable<short> kangrubu_id { get; set; }
        public Nullable<short> cinsiyet_id { get; set; }
        public Nullable<int> elbisebeden { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> cikistarihi { get; set; }
        public string image { get; set; }

        public virtual cinsiyet cinsiyet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giriscikis> giriscikis { get; set; }
        public virtual kangrup kangrup { get; set; }
        public virtual medenihali medenihali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel> personel { get; set; }
        public virtual personelbolum personelbolum { get; set; }
        public virtual personelegitim personelegitim { get; set; }
        public virtual personelgorev personelgorev { get; set; }
        public virtual personelgrup personelgrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personelsicaklik> personelsicaklik { get; set; }
    }
}
