//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.guvenlikkontrol = new HashSet<guvenlikkontrol>();
        }

        public int id { get; set; }
        public Nullable<int> kisi_id { get; set; }
        public string plaka { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy HH:mm}")]
        public Nullable<System.DateTime> giris { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy HH:mm}")]
        public Nullable<System.DateTime> cikis { get; set; }
        public string sebep { get; set; }
        public Nullable<int> isdisable { get; set; }
        public string username { get; set; }
        public Nullable<int> giris_id { get; set; }
        public Nullable<int> cikis_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guvenlikkontrol> guvenlikkontrol { get; set; }
        public virtual personelgenel personelgenel { get; set; }
    }
}
